data<-read.delim(file='household_power_consumption.txt', header = TRUE, sep = ";", dec = ".")
data$Datetime<-paste(data$Date,data$Time,sep=" ")
data$Datetime<-strptime(x=as.character(data$Datetime),format='%d/%m/%Y %H:%M:%S')
data2<-data[data$Datetime>=as.POSIXct("2007-02-01 00:00:00", tz="Asia/Singapore"),]
data2<-data2[data2$Datetime<as.POSIXct("2007-02-03 00:00:00", tz="Asia/Singapore"),]
data2$Sub_metering_1<-as.numeric(as.character(data2$Sub_metering_1))
data2$Sub_metering_2<-as.numeric(as.character(data2$Sub_metering_2))
data2$Sub_metering_3<-as.numeric(as.character(data2$Sub_metering_3))
png(file = "plot3.png")
plot(data2$Datetime,data2$Sub_metering_1,type='l',ylab='Energy sub metering',xlab='')
lines(data2$Datetime,data2$Sub_metering_1,col='black',lwd=1)
lines(data2$Datetime,data2$Sub_metering_2,col='red',lwd=1)
lines(data2$Datetime,data2$Sub_metering_3,col='blue',lwd=1)
legend('topright',c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lwd=c(1,1,1), col=c('black','red','blue')) 
dev.off()