data<-read.delim(file='household_power_consumption.txt', header = TRUE, sep = ";", dec = ".")
data$Datetime<-paste(data$Date,data$Time,sep=" ")
data$Datetime<-strptime(x=as.character(data$Datetime),format='%d/%m/%Y %H:%M:%S')
data2<-data[data$Datetime>=as.POSIXct("2007-02-01 00:00:00", tz="Asia/Singapore"),]
data2<-data2[data2$Datetime<as.POSIXct("2007-02-03 00:00:00", tz="Asia/Singapore"),]
data2$Sub_metering_1<-as.numeric(as.character(data2$Sub_metering_1))
data2$Sub_metering_2<-as.numeric(as.character(data2$Sub_metering_2))
data2$Sub_metering_3<-as.numeric(as.character(data2$Sub_metering_3))
data2$Voltage<-as.numeric(as.character(data2$Voltage))
data2$Global_active_power<-as.numeric(as.character(data2$Global_active_power))
data2$Global_reactive_power<-as.numeric(as.character(data2$Global_reactive_power))
png(file = "plot4.png")
par(mfrow=c(2,2))
plot(data2$Datetime,data2$Global_active_power,type='l',ylab="Global Active Power (kilowatts)",xlab="")
plot(data2$Datetime,data2$Voltage,type='l',ylab='Voltage',xlab='datetime')
plot(data2$Datetime,data2$Sub_metering_1,type='l',ylab="Energy sub metering",xlab="")
lines(data2$Datetime,data2$Sub_metering_2,col='red',lwd=1)
lines(data2$Datetime,data2$Sub_metering_3,col='blue',lwd=1)
legend('topright',c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lwd=c(1,1,1), col=c('black','red','blue'))
plot(data2$Datetime,data2$Global_reactive_power,type='l',ylab='Global_reactive_power',xlab='datetime')
dev.off()